# Generated by Django 4.2.5 on 2023-10-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_privacyresource_privacysetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="major",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
