# Generated by Django 4.2.7 on 2023-11-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_privacyresource_privacysetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="major",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
