# fly.toml app configuration file generated for platform-frontend on 2023-10-31T09:32:36-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "platform-frontend"
primary_region = "ewr"

[build]
  image = "pennlabs/platform-frontend:latest"

[env]
  DOMAIN = "platform-backend.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
