# Generated by Django 2.0.8 on 2018-11-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='update',
            name='product',
        ),
        migrations.DeleteModel(
            name='Update',
        ),
    ]
