# Generated by Django 2.1 on 2018-08-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='location',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
