# Generated by Django 2.1 on 2018-08-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180829_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
