# Generated by Django 2.0.7 on 2018-09-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
