# Generated by Django 2.0.8 on 2018-10-14 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20181014_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('photo', models.URLField()),
                ('linkedin', models.URLField()),
                ('website', models.URLField()),
                ('github', models.URLField()),
                ('year_joined', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='labmember',
            name='user',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Team',
        ),
        migrations.DeleteModel(
            name='LabMember',
        ),
        migrations.AddField(
            model_name='member',
            name='teams',
            field=models.ManyToManyField(to='api.Team'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
