# Generated by Django 2.0.8 on 2018-10-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('api', '0008_auto_20181014_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(),
        ),
    ]
