# Generated by Django 2.0.8 on 2018-10-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181014_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='alumnus',
            field=models.BooleanField(default=False),
        ),
    ]
