# Generated by Django 2.1.2 on 2018-10-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181024_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='role',
        ),
        migrations.AddField(
            model_name='member',
            name='roles',
            field=models.ManyToManyField(to='api.Role'),
        ),
    ]
