# Generated by Django 2.1.2 on 2018-10-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181028_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='url',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
