# Generated by Django 2.1.2 on 2018-10-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_member_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='url',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
