# Generated by Django 2.1.2 on 2018-12-09 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.URLField()),
                ('icon', models.URLField()),
                ('notes', models.TextField(blank=True)),
                ('routes', models.ManyToManyField(to='services.Endpoint')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='org.Team')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.Service')),
            ],
        ),
    ]
