# Generated by Django 3.1.2 on 2020-10-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='routes',
        ),
        migrations.RemoveField(
            model_name='service',
            name='team',
        ),
        migrations.RemoveField(
            model_name='update',
            name='service',
        ),
        migrations.DeleteModel(
            name='Endpoint',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Update',
        ),
    ]
