# Generated by Django 2.1.2 on 2018-11-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20181104_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.URLField(default='https://pennlabs.org'),
            preserve_default=False,
        ),
    ]
