# Generated by Django 2.1.2 on 2018-11-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='product',
            new_name='service',
        ),
    ]
