# Generated by Django 2.2.4 on 2019-08-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='product_permission',
            field=models.ManyToManyField(blank=True, to='accounts.ProductPermission'),
        ),
    ]
