# Generated by Django 2.2 on 2019-04-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPermissions',
            new_name='ProductPermission',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='product_permissions',
            new_name='product_permission',
        ),
    ]
