# Generated by Django 3.1.2 on 2020-11-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201023_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='major',
            name='degree_type',
            field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], default='Bachelor', max_length=10),
        ),
    ]
