# Generated by Django 2.1.2 on 2019-01-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181210_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_uri', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('revoked', models.BooleanField(default=False)),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('hashed_secret', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
