# Generated by Django 3.1.5 on 2021-02-07 17:31

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20200213_1711"),
    ]

    operations = [
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "degree_type",
                    models.CharField(
                        choices=[
                            ("BACHELORS", "Bachelor's"),
                            ("MASTERS", "Master's"),
                            ("PHD", "PhD"),
                            ("PROFESSIONAL", "Professional"),
                        ],
                        default="PROFESSIONAL",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="graduation_year",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_name",
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.RemoveField(
            model_name="student",
            name="major",
        ),
        migrations.RemoveField(
            model_name="student",
            name="school",
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="student",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
        migrations.CreateModel(
            name="PhoneNumberModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, default=None, max_length=128, region=None, unique=True
                    ),
                ),
                ("primary", models.BooleanField(default=False)),
                ("verification_code", models.CharField(blank=True, max_length=6, null=True)),
                ("verification_timestamp", models.DateTimeField(blank=True, null=True)),
                ("verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("primary", models.BooleanField(default=False)),
                ("verification_code", models.CharField(blank=True, max_length=6, null=True)),
                ("verification_timestamp", models.DateTimeField(blank=True, null=True)),
                ("verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="major",
            field=models.ManyToManyField(to="accounts.Major"),
        ),
        migrations.AddField(
            model_name="student",
            name="school",
            field=models.ManyToManyField(to="accounts.School"),
        ),
    ]
