# Generated by Django 3.0.6 on 2020-05-19 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20200421_2056"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="student", name="graduation_year", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="preferred_name",
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
