# Generated by Django 3.1.2 on 2020-11-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201101_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='degree_type',
            field=models.CharField(choices=[("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ('PhD', 'PhD')], default="Bachelor's", max_length=10),
        ),
    ]
