# Generated by Django 3.1.5 on 2021-03-09 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210207_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_year',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1740)]),
            preserve_default=False,
        ),
    ]
