# Generated by Django 2.1.5 on 2019-02-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
