# Generated by Django 2.1.7 on 2019-02-23 03:02

from django.db import migrations, models
from accounts.models import Student
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_application'),
    ]

    def generate_uuid(apps, schema_editor):
        for student in Student.objects.all():
            student.uuid = uuid.uuid4()
            student.save()

    operations = [
        migrations.AddField(
            model_name='student',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(generate_uuid),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
