# Generated by Django 3.1.2 on 2020-11-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201101_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ManyToManyField(to='accounts.School'),
        ),
    ]
