# Generated by Django 3.1.7 on 2021-03-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20210311_1354"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="major",
            field=models.ManyToManyField(blank=True, null=True, to="accounts.Major"),
        ),
        migrations.AlterField(
            model_name="student",
            name="school",
            field=models.ManyToManyField(blank=True, null=True, to="accounts.School"),
        ),
    ]
