# Generated by Django 3.0.6 on 2020-08-19 01:41

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0005_auto_20200729_0227")]

    operations = [
        migrations.AlterField(
            model_name="phonenumbermodel",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True
            ),
        )
    ]
