# Generated by Django 3.1.5 on 2021-03-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210310_1648'),
        ('accounts', '0005_auto_20210311_1354'),
    ]

    operations = [
    ]
