# Generated by Django 3.1.7 on 2021-04-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210321_1202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneNumberModel',
            new_name='PhoneNumber',
        ),
    ]
