# Generated by Django 3.1.7 on 2021-09-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210918_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ManyToManyField(blank=True, to='accounts.Major'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ManyToManyField(blank=True, to='accounts.School'),
        ),
    ]
