# Generated by Django 3.1.2 on 2020-10-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201018_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
