# Generated by Django 3.1.2 on 2020-10-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_major_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='major',
            old_name='active',
            new_name='is_active',
        ),
    ]
