# Generated by Django 2.0.8 on 2018-11-26 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('founded', models.DateTimeField()),
                ('verified', models.BooleanField()),
                ('contact', models.EmailField(max_length=254)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='engagement.Club')),
            ],
        ),
    ]
