# Generated by Django 2.0.8 on 2018-11-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_auto_20181126_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='route',
        ),
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
