# Generated by Django 2.1.2 on 2018-12-05 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engagement', '0003_auto_20181126_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='fact',
            field=models.CharField(default='Fun Fact about this club', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.SlugField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
