# Generated by Django 2.2.4 on 2019-09-04 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='tagline',
        ),
    ]
