# Generated by Django 2.1.2 on 2018-12-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['student__name']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='user',
            new_name='student',
        ),
        migrations.AddField(
            model_name='role',
            name='order',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='order',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
