# Generated by Django 2.1.2 on 2018-12-08 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_auto_20181116_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='teams',
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='org.Team'),
        ),
    ]
