# Generated by Django 2.2.4 on 2019-09-04 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_remove_team_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='url',
        ),
    ]
