# Generated by Django 3.1.2 on 2020-10-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_auto_20190904_0012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
