# Generated by Django 4.2.7 on 2023-11-09 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audience",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("MOBILE", "Penn Mobile"),
                            ("OHQ", "OHQ"),
                            ("CLUBS", "Penn Clubs"),
                            ("COURSE_PLAN", "Penn Course Plan"),
                            ("COURSE_REVIEW", "Penn Course Review"),
                            ("COURSE_ALERT", "Penn Course Alert"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("message", models.TextField()),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[("NOTICE", "Notice"), ("ISSUE", "Issue")],
                        default="NOTICE",
                        max_length=20,
                    ),
                ),
                (
                    "release_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "audiences",
                    models.ManyToManyField(
                        related_name="announcements", to="announcements.audience"
                    ),
                ),
            ],
        ),
    ]
