# Generated by Django 3.2.21 on 2023-10-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="announcement_type",
            field=models.CharField(
                choices=[("NOTICE", "Notice"), ("ISSUE", "Issue")],
                default="NOTICE",
                max_length=20,
            ),
        ),
    ]
