# Generated by Django 4.2.7 on 2023-11-05 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0002_alter_announcement_announcement_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="release_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
